spring:
   application:
      name: authentication-service
   config:
      import: optional:configserver:http://localhost:8888

   datasource:
      url: jdbc:postgresql://localhost:5432/user_db
      username: postgres
      password: utkarsh
      driverClassName: org.postgresql.Driver
   jpa:
#      spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
         ddl-auto: create
 #    show-sql: true
      properties:
         hibernate:
            format_sql: true
            default_schema: user_auth_service
      database: POSTGRESQL
      database-platform: org.hibernate.dialect.PostgreSQLDialect
#   h2:
#      console:
#         enabled: true
#         path: /db-console

   main:
      allow-bean-definition-overriding: true
      allow-circular-references: true

   messages:
      basename:
   jta:
      atomikos:
         connectionfactory:
            maintenance-interval:

server:
   servlet:
      context-path: /api
   port: 8081

app:
   auth-type: DAO

eureka:
   instance:
       instance-id: ${spring.application.name}:${server.port}
       preferIpAddress: true
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: http://localhost:8761/eureka

#logging:
#   level:
#      org.springframework: DEBUG

management:
   endpoints:
      web:
         exposure:
            include: health,info,beans