spring:
    application:
        name: api-gateway

    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: service-name
                  uri: http://localhost:8654 # actual service url without eureka
                  predicates:
                    - Path=/api/v1/carts/**


server:
    servlet:
        context-path: /api/gateway
    port: 8000

eureka:
    instance:
        instance-id: ${spring.application.name}:${random.value}
        preferIpAddress: true
    client:
        register-with-eureka: true
        fetch-registry: true

    service-url:
        defaultZone: http://localhost:8761/eureka

logging:
    level:
        org.springframework.web: DEBUG

management:
    endpoints:
        web:
            exposure:
                include: health,info,beans