spring:
   application:
      name: product-service
   config:
      import: optional:configserver:http://localhost:8888

# Application Configs

app:
   external:
      api: https://fakestoreapi.com
      product-endpoint: ${app.external.api}/products
      category-endpoint: ${app.external.api}/products/category

# Spring Server Configs
server:
   servlet:
      context-path: /api
   port: 8084

# Eureka Server Config
eureka:
   instance:
      instance-id: ${spring.application.name}:${server.port}
      preferIpAddress: true
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: http://localhost:8761/eureka

management:
   endpoints:
      web:
         exposure:
            include: health,info,beans
         base-path: ${server.servlet.context-path}/actuator