# Application Configs

app:
   external:
      api: https://fakestoreapi.com
      cart-endpoint: ${app.external.api}/carts
      category-endpoint: ${app.external.api}/carts/category


# Spring Server Configs
server:
   port:  8081
   servlet:
      context-path: /api

   error:
      include-stacktrace: never

# Eureka Server Config
eureka:
   instance:
      instance-id: ${spring.application.name}:${random.value}
   client:
      register-with-eureka: false
      fetch-registry: false

   service-url:
      defaultZone: http://localhost:8761/eureka

spring:
   application:
      name: cart-service