spring:
   application:
      name: config-server

   profiles:
      active: native

   cloud:
      config:
         server:
            native:
               search-locations: classpath:/configurations
#            accept-empty: false
#            git:
#               uri: file://C:/workspace/ms-project1/config-repo
#               default-label: master
#               #clone-on-start: false
#               basedir: config-repo
#               search-paths: '{application}' # maps to spring.application.name

server:
   port: 8888